apiVersion: v1
kind: Service
metadata:
 name: dev-nextcloud-cicd
 namespace: default
 spec:
  clusterIP: 10.43.235.2
  clusterIPs:
  - 10.43.235.2
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    workload.user.cattle.io/workloadselector: apps.deployment-default-dev-nextcloud
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
